---
# up to now only for centos/redhat

- name: Install nfs utils package on RedHat
  ansible.builtin.yum:
    name: nfs-utils
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure rpcbind is running.
  ansible.builtin.service:
    name: rpcbind
    state: started
    enabled: yes

- name: Stat the exports file /etc/exports
  ansible.builtin.stat:
    path: /etc/exports
  register: exportsfile

- name: Stat the exports file /etc/exports.d/zfs.exports which is also used by openzfs
  ansible.builtin.stat:
    path: /etc/exports.d/zfs.exports
  register: zfsexportsfile

# - debug:
#    msg: "exportsfile is  {{ exportsfile.stat.size }} bytes,
#    # zfsexportsfile is {{ zfsexportsfile.stat.size }} bytes"
#  when: exportsfile.stat.exists

- name: Ensure nfs is running if exports files are bigger than 0 byte
  ansible.builtin.service:
    name: "{{ nfs_service_name }}"
    state: started
    enabled: yes
  when: nfs_share_mounts|length > 0
    or
    exportsfile.stat.exists and exportsfile.stat.size > 0
    or
    zfsexportsfile.stat.exists and zfsexportsfile.stat.size > 0

# needs ansible-galaxy collection install ansible.posix
- name: Mount NFS share(s)
  become: yes
  ansible.posix.mount:
    fstype: nfs4
    name: "{{ item.path }}"
    opts: "{{ item.opts | default(nfs_mount_opts) }}"
    src: "{{ item.location }}"
    state: mounted
  with_items: "{{ nfs_share_mounts }}"

- name: Ensure that the NFS mount points exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: '{{ item.owner | d("root") }}'
    group: '{{ item.group | d("root") }}'
    # mode: # is set from original folder!?
    state: "directory"
  with_items: "{{ nfs_share_mounts }}"
